import json
from app.services.workflow import graph_app

async def ask_database(query: str) -> str:
    """
    Entrypoint for the API.
    Invokes the LangGraph orchestrator which routes and processes the query.
    """
    try:
        # Start the graph with the initial state
        result = await graph_app.ainvoke({"input_query": query})
        
        # Return the final response generated by the graph
        return result.get("final_response", "I could not generate a response.")
    except Exception as e:
        return f"System Error: {str(e)}"

async def stream_database(query: str):
    """
    Streaming entrypoint for the UI.
    Yields Server-Sent Events (SSE) detailing the agent's thought process.
    """
    try:
        # We use astream with stream_mode="updates" to get events as nodes finish
        async for state_update in graph_app.astream({"input_query": query}, stream_mode="updates"):
            # state_update is a dict where the key is the node name that just finished
            for node_name, node_state in state_update.items():
                
                # Format a friendly progress message based on the node
                if node_name == "router":
                    intent = node_state.get("intent", "UNKNOWN")
                    yield f"data: {json.dumps({'type': 'step', 'message': f'Classified intent as {intent}. Routing...'})}\n\n"
                
                elif node_name in ["company", "user", "vessel", "defect"]:
                    yield f"data: {json.dumps({'type': 'step', 'message': f'Querying {node_name} database module natively using Prisma...'})}\n\n"
                    
                elif node_name == "casual":
                    yield f"data: {json.dumps({'type': 'step', 'message': 'Generating conversational response...'})}\n\n"
                    
                elif node_name == "out_of_scope":
                    yield f"data: {json.dumps({'type': 'step', 'message': 'Identifying irrelevant query...'})}\n\n"
                    
                elif node_name == "formatter":
                    yield f"data: {json.dumps({'type': 'step', 'message': 'Formatting exact text markdown response...'})}\n\n"

                # Check if this node produced the final answer
                if "final_response" in node_state:
                    final_text = node_state["final_response"]
                    yield f"data: {json.dumps({'type': 'result', 'message': final_text})}\n\n"
                    
    except Exception as e:
        yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
